// /*
// Auto-generated by: https://github.com/pmndrs/gltfjsx
// */

// import * as THREE from "three";
// import React, { useRef } from "react";
// import { useGLTF } from "@react-three/drei";
// import { GLTF } from "three-stdlib";
// import { useTrimesh } from "@react-three/cannon";

// type GLTFResult = GLTF & {
//   nodes: {
//     Text: THREE.Mesh;
//   };
//   materials: {};
// };

// export function Date2(props: JSX.IntrinsicElements["group"]) {
//   const { nodes, materials } = useGLTF("./83/83.glb") as GLTFResult;

//   const [ref, api] = useTrimesh(
//     () => ({
//       args: [
//         nodes.Text.geometry.attributes.position.array,
//         nodes.Text.geometry.index.array,
//       ],
//       mass: 1,
//       ...props,
//     }),
//     useRef<THREE.Group>(null!)
//   );
//   return (
//     <group {...props} dispose={null} ref={ref}>
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.Text.geometry}
//         material={nodes.Text.material}
//       />
//     </group>
//   );
// }

// useGLTF.preload("./83/83.glb");
